In [6]:
import numpy as np
url=(r"C:\Users\LENOVO\Desktop\pdf&word\python\libraries\amazon.csv")
url
amazon=np.genfromtxt(url,delimiter=',',dtype=[('year','i8'),('state','S200'),('month','S20'),('number','f8'),('date','S10')])
names=('year','state','month','number','date')
amazon


array([(  -1, b'"state"', b'"month"',  nan, b'"date"'),
       (1998, b'"Acre"', b'"Janeiro"',   0., b'1998-01-01'),
       (1999, b'"Acre"', b'"Janeiro"',   0., b'1999-01-01'), ...,
       (2014, b'"Tocantins"', b'"Dezembro"', 223., b'2014-01-01'),
       (2015, b'"Tocantins"', b'"Dezembro"', 373., b'2015-01-01'),
       (2016, b'"Tocantins"', b'"Dezembro"', 119., b'2016-01-01')],
      dtype=[('year', '<i8'), ('state', 'S200'), ('month', 'S20'), ('number', '<f8'), ('date', 'S10')])

In [5]:
print(amazon['state'])

[b'"state"' b'"Acre"' b'"Acre"' ... b'"Tocantins"' b'"Tocantins"'
 b'"Tocantins"']


In [25]:
import numpy as np
url=(r"C:/users/LENOVO/Desktop/pdf&word/python/libraries/amazon.csv")
amazon1=np.genfromtxt(url,delimiter=',',dtype='float',usecols=[0,1,2,3])
a=np.any(np.isnan(amazon1))
print(a)
b=amazon1[np.isnan(amazon1)]=0#because isnan is character and will not do mathematical operations
print(amazon1)


True
[[   0.    0.    0.    0.]
 [1998.    0.    0.    0.]
 [1999.    0.    0.    0.]
 ...
 [2014.    0.    0.  223.]
 [2015.    0.    0.  373.]
 [2016.    0.    0.  119.]]


In [7]:
print("the average forest fire from 1988 to 2017 is: ",np.mean(amazon1[1:,[3]]))

the average forest fire from 1988 to 2017 is:  108.29316284474744


In [27]:
print("the total number of forest fire from 1988 to 2017 is: ",np.sum(amazon1[1:,[3]]))

the total number of forest fire from 1988 to 2017 is:  698924.073


In [31]:
print("the median of forest fire is: ",np.median(amazon1[1:,[3]]))

the median of forest fire is:  24.0


In [35]:
print(amazon1[1:,[0,3]])

[[1998.    0.]
 [1999.    0.]
 [2000.    0.]
 ...
 [2014.  223.]
 [2015.  373.]
 [2016.  119.]]


In [44]:
a=print("forest fire less than 30 is: ",amazon1[amazon1[0:,3]<5])
print(a)

forest fire less than 30 is:  [[0.000e+00 0.000e+00 0.000e+00 0.000e+00]
 [1.998e+03 0.000e+00 0.000e+00 0.000e+00]
 [1.999e+03 0.000e+00 0.000e+00 0.000e+00]
 ...
 [2.016e+03 0.000e+00 0.000e+00 2.032e+00]
 [2.017e+03 0.000e+00 0.000e+00 2.969e+00]
 [1.998e+03 0.000e+00 0.000e+00 1.000e+00]]
None


In [43]:
print(np.percentile(amazon1[0:,3],25))

3.0


In [50]:
print(amazon1[amazon1[:,3].argsort()][::-1])

[[2008.    0.    0.  998.]
 [2006.    0.    0.  995.]
 [2012.    0.    0.  995.]
 ...
 [2007.    0.    0.    0.]
 [2013.    0.    0.    0.]
 [   0.    0.    0.    0.]]
