In [53]:
import numpy as np
url=(r"C:/users/LENOVO/Desktop/pdf&word/python/libraries/irisdataset.csv")
url
iris=np.genfromtxt(url,delimiter=',',dtype=[('sepallength','f4'),('sepalwidth','f4'),('petallength','f4'),('petalwidth','f4'),('species','S20')])
names=('sepallength','sepalwidth','petallength','petalwidth','species')
iris

array([(nan, nan, nan, nan, b'species'), (5.1, 3.5, 1.4, 0.2, b'setosa'),
       (4.9, 3. , 1.4, 0.2, b'setosa'), (4.7, 3.2, 1.3, 0.2, b'setosa'),
       (4.6, 3.1, 1.5, 0.2, b'setosa'), (5. , 3.6, 1.4, 0.2, b'setosa'),
       (5.4, 3.9, 1.7, 0.4, b'setosa'), (4.6, 3.4, 1.4, 0.3, b'setosa'),
       (5. , 3.4, 1.5, 0.2, b'setosa'), (4.4, 2.9, 1.4, 0.2, b'setosa'),
       (4.9, 3.1, 1.5, 0.1, b'setosa'), (5.4, 3.7, 1.5, 0.2, b'setosa'),
       (4.8, 3.4, 1.6, 0.2, b'setosa'), (4.8, 3. , 1.4, 0.1, b'setosa'),
       (4.3, 3. , 1.1, 0.1, b'setosa'), (5.8, 4. , 1.2, 0.2, b'setosa'),
       (5.7, 4.4, 1.5, 0.4, b'setosa'), (5.4, 3.9, 1.3, 0.4, b'setosa'),
       (5.1, 3.5, 1.4, 0.3, b'setosa'), (5.7, 3.8, 1.7, 0.3, b'setosa'),
       (5.1, 3.8, 1.5, 0.3, b'setosa'), (5.4, 3.4, 1.7, 0.2, b'setosa'),
       (5.1, 3.7, 1.5, 0.4, b'setosa'), (4.6, 3.6, 1. , 0.2, b'setosa'),
       (5.1, 3.3, 1.7, 0.5, b'setosa'), (4.8, 3.4, 1.9, 0.2, b'setosa'),
       (5. , 3. , 1.6, 0.2, b'setosa'), (5. , 3.4,

In [9]:
print(iris[0:,[0,1]])

[[b'\xef\xbb\xbfsepal_length' b'sepal_width']
 [b'5.1' b'3.5']
 [b'4.9' b'3']
 [b'4.7' b'3.2']
 [b'4.6' b'3.1']
 [b'5' b'3.6']
 [b'5.4' b'3.9']
 [b'4.6' b'3.4']
 [b'5' b'3.4']
 [b'4.4' b'2.9']
 [b'4.9' b'3.1']
 [b'5.4' b'3.7']
 [b'4.8' b'3.4']
 [b'4.8' b'3']
 [b'4.3' b'3']
 [b'5.8' b'4']
 [b'5.7' b'4.4']
 [b'5.4' b'3.9']
 [b'5.1' b'3.5']
 [b'5.7' b'3.8']
 [b'5.1' b'3.8']
 [b'5.4' b'3.4']
 [b'5.1' b'3.7']
 [b'4.6' b'3.6']
 [b'5.1' b'3.3']
 [b'4.8' b'3.4']
 [b'5' b'3']
 [b'5' b'3.4']
 [b'5.2' b'3.5']
 [b'5.2' b'3.4']
 [b'4.7' b'3.2']
 [b'4.8' b'3.1']
 [b'5.4' b'3.4']
 [b'5.2' b'4.1']
 [b'5.5' b'4.2']
 [b'4.9' b'3.1']
 [b'5' b'3.2']
 [b'5.5' b'3.5']
 [b'4.9' b'3.1']
 [b'4.4' b'3']
 [b'5.1' b'3.4']
 [b'5' b'3.5']
 [b'4.5' b'2.3']
 [b'4.4' b'3.2']
 [b'5' b'3.5']
 [b'5.1' b'3.8']
 [b'4.8' b'3']
 [b'5.1' b'3.8']
 [b'4.6' b'3.2']
 [b'5.3' b'3.7']
 [b'5' b'3.3']
 [b'7' b'3.2']
 [b'6.4' b'3.2']
 [b'6.9' b'3.1']
 [b'5.5' b'2.3']
 [b'6.5' b'2.8']
 [b'5.7' b'2.8']
 [b'6.3' b'3.3']
 [b'4.9' b'2.4']


In [27]:
import numpy as np
url=(r"C:/users/LENOVO/Desktop/pdf&word/python/libraries/irisdataset.csv")
iris1=np.genfromtxt(url,delimiter=',',dtype='float',usecols=[0,1,2,3])
names=('sepallength','sepalwidth','petallength','petalwidth','species')
np.any(np.isnan(iris1))
iris1[np.isnan(iris1)]=0 #because isnan is character and will not do mathematical operations
print("mean of sepallength is: ",np.mean(iris1[1:,[0]]))
print("mean of petallength is: ",np.mean(iris1[1:,[2]]))
print("median of sepallength is: ",np.median(iris1[1:,[0]]))
print("median of petallength is: ",np.median(iris1[1:,[2]]))
print("standard deviation of sepallength is: ",np.std(iris1[1:,[0]]))
print("standard deviation of petallength is: ",np.std(iris1[1:,[2]]))

print("petallength greater than 1.5 is: ",iris1[iris1[0:,2]>1.5])

mean of sepallength is:  5.843333333333334
mean of petallength is:  3.758666666666666
median of sepallength is:  5.8
median of petallength is:  4.35
standard deviation of sepallength is:  0.8253012917851409
standard deviation of petallength is:  1.7585291834055212
petallength greater than 1.5 is:  [[5.4 3.9 1.7 0.4]
 [4.8 3.4 1.6 0.2]
 [5.7 3.8 1.7 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [5.1 3.8 1.6 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.  1.3]
 [6.5 2.8 4.6 1.5]
 [5.7 2.8 4.5 1.3]
 [6.3 3.3 4.7 1.6]
 [4.9 2.4 3.3 1. ]
 [6.6 2.9 4.6 1.3]
 [5.2 2.7 3.9 1.4]
 [5.  2.  3.5 1. ]
 [5.9 3.  4.2 1.5]
 [6.  2.2 4.  1. ]
 [6.1 2.9 4.7 1.4]
 [5.6 2.9 3.6 1.3]
 [6.7 3.1 4.4 1.4]
 [5.6 3.  4.5 1.5]
 [5.8 2.7 4.1 1. ]
 [6.2 2.2 4.5 1.5]
 [5.6 2.5 3.9 1.1]
 [5.9 3.2 4.8 1.8]
 [6.1 2.8 4.  1.3]
 [6.3 2.5 4.9 1.5]
 [6.1 2.8 4.7 1.2

In [29]:
n5=print("sepalength less tahn 5 is: ",iris1[iris1[0:,0]<5])
print(n5)

sepalength less tahn 5 is:  [[0.  0.  0.  0. ]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [4.6 3.4 1.4 0.3]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [4.6 3.6 1.  0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 3.1 1.5 0.1]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [4.8 3.  1.4 0.3]
 [4.6 3.2 1.4 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]
None


In [38]:
print(np.corrcoef(iris1[0:,0],iris1[0:,2])[0,1]) #filter the values
print(np.unique(iris1[0:,0],return_counts='TRUE'))

0.8297223070681915
(array([0. , 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1, 5.2, 5.3, 5.4,
       5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4, 6.5, 6.6, 6.7,
       6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.6, 7.7, 7.9]), array([ 1,  1,  3,  1,  4,  2,  5,  6, 10,  9,  4,  1,  6,  7,  6,  8,  7,
        3,  6,  6,  4,  9,  7,  5,  2,  8,  3,  4,  1,  1,  3,  1,  1,  1,
        4,  1], dtype=int64))


In [33]:
print(np.percentile(iris1[0:,0],25))#means 25% of values are below this number

5.1


In [64]:
#np.sort(iris1[0:,1])
#np.sort(iris1)[::-1]
#np.sort(iris,order='sepallength')[::-1]
iris1[iris1[:,2].argsort()][::-1]

array([[7.7, 2.6, 6.9, 2.3],
       [7.7, 2.8, 6.7, 2. ],
       [7.7, 3.8, 6.7, 2.2],
       [7.6, 3. , 6.6, 2.1],
       [7.9, 3.8, 6.4, 2. ],
       [7.3, 2.9, 6.3, 1.8],
       [7.2, 3.6, 6.1, 2.5],
       [7.7, 3. , 6.1, 2.3],
       [7.4, 2.8, 6.1, 1.9],
       [7.2, 3.2, 6. , 1.8],
       [6.3, 3.3, 6. , 2.5],
       [6.8, 3.2, 5.9, 2.3],
       [7.1, 3. , 5.9, 2.1],
       [6.5, 3. , 5.8, 2.2],
       [7.2, 3. , 5.8, 1.6],
       [6.7, 2.5, 5.8, 1.8],
       [6.7, 3.3, 5.7, 2.1],
       [6.9, 3.2, 5.7, 2.3],
       [6.7, 3.3, 5.7, 2.5],
       [6.4, 2.8, 5.6, 2.2],
       [6.3, 2.9, 5.6, 1.8],
       [6.1, 2.6, 5.6, 1.4],
       [6.4, 2.8, 5.6, 2.1],
       [6.7, 3.1, 5.6, 2.4],
       [6.3, 3.4, 5.6, 2.4],
       [6.5, 3. , 5.5, 1.8],
       [6.8, 3. , 5.5, 2.1],
       [6.4, 3.1, 5.5, 1.8],
       [6.2, 3.4, 5.4, 2.3],
       [6.9, 3.1, 5.4, 2.1],
       [6.4, 3.2, 5.3, 2.3],
       [6.4, 2.7, 5.3, 1.9],
       [6.7, 3. , 5.2, 2.3],
       [6.5, 3. , 5.2, 2. ],
       [5.8, 2